name: CI
on:
  push:
    branches: [ main ]
  pull_request: 

jobs:
  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    
    - name: Set up virtual environment and install dependencies
      run: |
        uv venv
        uv sync
    
    - name: Run ruff check
      run: uvx ruff check
